esphome:
  name: a1s
  friendly_name: A1S


esp32:
  board: esp-wrover-kit
  framework:
    type: arduino
 
logger:
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


i2c:
  sda: GPIO33
  scl: GPIO32

external_components:
  - source: github://mulcmu/esphome-es8388-a1s
    components: [es8388]

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO27

es8388:
media_player:
  - platform: i2s_audio
    name: "ESP32 Audio Kit"
    #i2s_lrclk_pin: GPIO25
    i2s_dout_pin: GPIO26
    #i2s_bclk_pin: GPIO27
    dac_type: external
    mode: stereo

 
switch:
  - platform: gpio
    pin: GPIO21
    name: "AMP Switch"
    restore_mode: ALWAYS_ON

    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true
    name: "on_hook"

  - platform: gpio
    pin:
      number: GPIO036
      inverted: true
    name: "Key 1"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO013
      inverted: true
    name: "Key 2"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO019
      inverted: true
   #   allow_other_uses: true
    name: "Key 3"
    filters:
      - delayed_off: 10ms
      
  - platform: gpio
    pin:
      number: GPIO023
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 4"
    filters:
      - delayed_off: 10ms
      
  - platform: gpio
    pin:
      number: GPIO018
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 5"
    filters:
      - delayed_off: 10ms
      
  - platform: gpio
    pin:
      number: GPIO005
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 6"
    filters:
      - delayed_off: 10ms

#light:
#  - platform: binary
#    name: "Test LED 1"
#    output: light_output_1
#  - platform: binary
#    name: "Test LED 2"
#    output: light_output_2
 
#output:
#  - id: light_output_1
#    platform: gpio
#    pin: GPIO22
#    inverted: true
#  - id: light_output_2
#    platform: gpio
#    pin: 
#      number: GPIO19
#      allow_other_uses: true
#    inverted: true
